backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
  - name: "porteroConfig"
    label: "Configuración Portero"
    files:
      - file: "config.json"
        name: "settings"
        label: "Datos de la Configuración"
        format: "json"
        fields:
          - label: "GPS requerido"
            name: "geo_required"
            widget: "boolean"
            default: true
          - label: "Latitud del edificio"
            name: "building_lat"
            widget: "string"
            default: "18.456789"
            hint: "Usa punto decimal, ej. 18.456789"
          - label: "Longitud del edificio"
            name: "building_lng"
            widget: "string"
            default: "-69.123456"
            hint: "Usa punto decimal y signo menos si aplica"
          - label: "Radio permitido (m)"
            name: "allow_radius_m"
            widget: "number"
            default: 30
          - label: "Apartamentos"
            name: "apartamentos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "name", widget: "string" }
              - { label: "Activo", name: "active", widget: "boolean" }
              - { label: "Teléfono", name: "phone", widget: "string" }
              - { label: "Jitsi", name: "jitsi", widget: "string" }
