backend:
  name: git-gateway
  branch: main
media_folder: "uploads"
public_folder: "/uploads"
collections:
  - name: "porteroConfig"
    label: "Configuración Portero"
    files:
      - file: "config.json"
        name: "settings"
        label: "Datos de la Configuración"
        format: "json"
        fields:
          - label: "GPS requerido"
            name: "geo_required"
            widget: "boolean"
            default: true
          - label: "Latitud del edificio"
            name: "building_lat"
            widget: "number"
            default: 18.456789
            min: -90
            max: 90
            step: 0.000001
          - label: "Longitud del edificio"
            name: "building_lng"
            widget: "number"
            default: -69.123456
            min: -180
            max: 180
            step: 0.000001
          - label: "Radio permitido (m)"
            name: "allow_radius_m"
            widget: "number"
            default: 30
          - label: "Apartamentos"
            name: "apartamentos"
            widget: "list"
            fields:
              - { label: "Nombre", name: "name", widget: "string" }
              - { label: "Activo", name: "active", widget: "boolean" }
              - { label: "Teléfono", name: "phone", widget: "string" }
              - { label: "Jitsi", name: "jitsi", widget: "string" }
